config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'activity#index'

  resource :session, only: %i[new create] do
    get 'create_guest'
  end
  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#signout'

  resources :users, except: [:index]
  get 'signup' => 'users#new'

  resources :games, only: %i[index new create show] do
    resources :likes

    post 'update_board'
    get 'play_again'
  end

  get 'games/invite/:invitation_token', to: 'games#invite', as: 'game_invite'
end

app/controllers/activity_controller.rb
# frozen_string_literal: true

class ActivityController < ApplicationController
  def index
    @pagy, @games = pagy(Game.order(created_at: :desc).includes(:players), items: 5)

    @games = current_player.assign_my_likes_to_games(@games) if current_player
  end
end

app/views/activity/_game.html.erb
<%= tag.div class: "game", id: dom_id(game) do %>
  <%= render "activity/game_details", game: game %>
  <%= render "activity/game_likes", game: game %>
<% end %>

app/views/activity/_game_details.html.erb
<%= tag.div class: "details", id: "#{dom_id(game)}_details" do %>
  <%= link_to game_path(game), data: { turbo_frame: '_top' } do %>
    <div>
      <span class="user">
        <%= game.players&.first&.username || 'Player 1' %>
      </span>
      <%= game.end_at? ? 'is playing' : 'played' %> aganist
      <span class="user">
        <%= game.players&.last&.username || 'Player 2' %>
      </span>
      <%= time_ago_in_words(game.start_at) %> ago
    </div>
  <% end %>
<% end %>

app/views/activity/_game_likes.html.erb
<div id="<%= dom_id(game) %>_likes">
  <% if like = game.my_like %>
    <%= button_to game_like_path(game, like), method: :delete do %>
      <%= image_tag("full-heart.svg") %>
      <%= tag.div id: "#{dom_id(game)}_likes_count" do %>
        <%= game.likes_count %>
      <% end %>
    <% end %>
  <% else %>
    <%= button_to game_likes_path(game) do %>
      <%= image_tag("empty-heart.svg") %>
      <%= tag.div id: "#{dom_id(game)}_likes_count" do %>
        <%= game.likes_count %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/activity/index.html.erb
<%= turbo_stream_from "activity" %>
<div class='activity_index text-slate-400' id="games">
  <%= turbo_frame_tag "games_page_#{@pagy.page}" do %>
    <%= render collection: @games,
               partial: "activity/game" %>
    <% if @pagy.next %>
      <%= turbo_frame_tag "games_page_#{@pagy.next}", src: root_path(page: @pagy.next), loading: :lazy do %>
        <div class="loader">Loading...</div>
      <% end %>
    <% end %>
  <% end %>
</div>