config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'activity#index'

  resource :session, only: %i[new create] do
    get 'create_guest'
  end
  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#signout'

  resources :users, except: [:index]
  get 'signup' => 'users#new'

  resources :games, only: %i[index new create show] do
    resources :likes

    post 'update_board'
    get 'play_again'
  end

  get 'games/invite/:invitation_token', to: 'games#invite', as: 'game_invite'
end

app/models/game.rb
# frozen_string_literal: true

require 'securerandom'

class Game < ApplicationRecord
  include ActionView::RecordIdentifier
  include GamesHelper

  attr_accessor :my_like

  enum :mode, ['2 Players', 'Online'] # , 'Player vs Computer', 'Computer vs Computer']
  enum :level, %w[Noobie Expert]

  has_many :likes, dependent: :destroy
  has_many :game_players, dependent: :destroy
  has_many :players, through: :game_players, dependent: :destroy

  belongs_to :current_player, class_name: 'Player', optional: true
  belongs_to :next_game, class_name: 'Game', optional: true

  after_create :generate_invitation_token

  after_create_commit lambda {
    broadcast_prepend_later_to 'activity', target: 'games',
                                           partial: 'activity/game'
  }
  after_update_commit lambda {
    broadcast_update_later_to 'game',
                              target: dom_id(self),
                              partial: 'games/game',
                              locals: { game: self, win_pattern: win_pattern(self) }
  }

  # Determine the possible types of game finish
  FINISH_TYPES = [
    { patterns: [[0, 4, 8], [2, 4, 6]], name: 'Diagonal' },
    { patterns: [[0, 3, 6], [1, 4, 7], [2, 5, 8]], name: 'Vertical' },
    { patterns: [[0, 1, 2], [3, 4, 5], [6, 7, 8]], name: 'Horizontal' }
  ].freeze

  # returns false if input is invalid
  # return true and calls next player if valid
  def input_to_board(spot)
    return false unless spot_valid?(spot) && win_type.nil?

    board[spot.to_i] = game_players.find_by(player: current_player).symbol
    self.moves = moves + 1

    save

    # calls next player
    next_player unless game_over?

    true
  end

  # Checks all game possibilities and returns true if game won or false if not
  def game_over?
    return true unless win_type.nil?

    if (type = check_patterns)
      update(win_type: type, end_at: Time.zone.now)
    elsif moves == 9
      update(win_type: { pattern: [], name: 'Tie', end_at: Time.zone.now }.to_json)
    end

    !win_type.nil?
  end

  private

  # generate invitation token for invited player access
  def generate_invitation_token
    # return unless game mode is online
    return unless Game.modes[mode] == 1

    update(invitation_token: SecureRandom.urlsafe_base64)
  end

  # checks who is current player and sets it to the other player
  def next_player
    player = current_player == players[0] ? players[1] : players[0]

    update(current_player: player)
  end

  # Check if spot is only a number, between 0 and 8 and not taken
  def spot_valid?(spot)
    /^\d$/.match?(spot) &&
      spot.to_i.between?(0, 8) &&
      !%w[X O].include?(board[spot.to_i])
  end

  # Iterate over each finish type pattern and return finish type if any
  def check_patterns
    finish_type = nil

    FINISH_TYPES.each do |type|
      line = type[:patterns].find { |l| check_line(l) }

      next if line.nil?

      finish_type = { pattern: line, name: type[:name] }.to_json
      break
    end

    finish_type
  end

  # check if line passed has only X or O to determine if game is over
  def check_line(pattern)
    spots = pattern.map { |spot_num| board[spot_num] }

    spots.none?(&:nil?) && spots.uniq.length == 1
  end
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  before_action :require_signin, except: %i[index show]
  before_action :set_game, only: %i[show update_board play_again]
  before_action :ensure_correct_user, only: %i[update_board]

  def index
    @pagy, @games = pagy(Game.order(created_at: :desc).includes(:players), items: params[:per_page] ||= 5,
                                                                           link_extra: 'data-turbo-action="advance"')

    @games = current_player.assign_my_likes_to_games(@games) if current_player
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(
      start_at: Time.zone.now, mode: game_params[:mode]&.to_i, level: game_params[:level]&.to_i
    )

    if @game.save
      prepare_game
      redirect_to @game
    else
      flash.now[:alert] = @game.errors.full_messages.first
      render :new, status: :unprocessable_entity
    end
  end

  def update_board
    if @game.input_to_board(params[:spot])
      render partial: 'games/game',
             locals: {
               game: @game,
               win_pattern: @win_pattern
             }
    else
      flash.now[:alert] = 'Invalid spot'
      render :flash
    end
  end

  def play_again
    new_game = Game.new(
      start_at: Time.zone.now, mode: @game.mode, level: @game.level,
      players: @game.players, current_player: @game.current_player
    )

    if new_game.save
      @game.update(next_game_id: new_game.id)
      new_game.update(invitation_token: nil)

      redirect_to game_path(new_game)
    else
      flash.now[:alert] = new_game.errors.full_messages.first
      render :show
    end
  end

  def invite
    @game = Game.find_by(invitation_token: params[:invitation_token])

    if @game && @game.game_players.find_by(player: current_player).nil?
      @game.game_players.create(player: current_player, symbol: 'O')
      @game.update(invitation_token: nil)
      redirect_to game_path(@game), notice: "Let's play!"
    elsif @game
      redirect_to game_path(@game), notice: 'You are already in this game'
    else
      redirect_to root_url, alert: 'Invalid invitation link'
    end
  end

  private

  def game_params
    params.require(:game).permit(:mode, :level)
  end

  def set_game
    @game = Game.find_by(id: params[:id] || params[:game_id])

    return if @game

    redirect_to root_url, alert: 'The game you are looking for does not exist'
  end

  def ensure_correct_user
    return if Game.modes[@game.mode].zero? || signed_in? && current_player == @game.current_player

    flash.now[:alert] = "It's not your turn"
    render :flash
  end

  def prepare_game
    case Game.modes[@game.mode]
    when 0
      player2 = Player.find_or_create_by(username: 'Player 2')
      @game.game_players.create([{ player: player2, symbol: 'O' }, { player: current_player, symbol: 'X' }])

      @game.update(current_player:)
    when 1
      @game.game_players.create(player: current_player, symbol: 'X')

      @game.update(current_player:)
    end
  end
end

app/helpers/games_helper.rb
# frozen_string_literal: true

module GamesHelper
  def win_pattern(game)
    return unless game.win_type

    JSON.parse(game.win_type)['pattern']
  end

  def board_rows(game)
    game.board.each_slice(3)
  end

  def class_for_spot(spot, game)
    "p-10 hover:shadow-inner #{'bg-green-200' if game.game_over? && win_pattern(game).include?(spot)}"
  end
end

app/views/games/_board.html.erb
<div class="grid divide-y-2 divide-gray-200">
  <% board_rows(game).each_with_index do |row, row_idx| %>
    <div class="grid grid-cols-3 divide-x-2 divide-gray-200">
      <% row.each_with_index do |spot, idx| %>
        <% spot_num = idx + (row_idx * 3) %>
        <%= button_to spot || "&nbsp;&nbsp;".html_safe,
                  game_update_board_path(game, spot: spot_num),
                  { 
                    class: class_for_spot(spot_num, game),
                    disabled: game.game_over? || !spot.nil?
                  } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/games/_game.html.erb
<%= turbo_frame_tag game do %>
  <% if game.invitation_token && current_user == game.players&.first&.user %>
    <h2>Waiting</h2>
    <h3 class="pt-4 text-slate-400 text-center text-lg">
      To start the game copy and share this link with second player:
    </h3>
    <h3 class="text-slate-400 text-center text-lg">
      <%= button_tag game.invitation_token, 
        class: 'hover:scale-110 focus:text-green-600 hover:text-primary text-blue-300 duration-500', 
        data: { controller: 'clipboard', clipboard_link_value: game_invite_url(game.invitation_token) } %>
    </h3>
  <% else %>
    <div class="flex flex-col gap-4 text-slate-400 text-center text-lg">
      <%= render 'games/board', game: game %>
      <% if game.game_over? %>
        <h2>Game Over!</h2>
        <h3>
          <%= game.current_player.username %> has won!
          <%= link_to 'Play again', game_play_again_path(game), data: { turbo: false } if game.players.find_by(id: current_player.id) && !game.next_game %>
          <%= link_to 'Next Game', game_path(game.next_game), data: { turbo: false } if game.next_game %>
        </h3>
      <% else %>
        <h3>
          It's <%= game.current_player.username %>'s turn
        </h3>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/games/flash.turbo_stream.erb
<%= turbo_stream.update 'flash', partial: 'layouts/flash' %>

app/views/games/new.html.erb
<div class="flex flex-col gap-2">
  <h2>New Game</h2>
  <h3 class="text-slate-400 text-center text-lg">
    Choose the desired game settings
  </h3>
  <%= form_with(model: @game, class: "user-form", data: { controller: "game-mode", action: "input->game-mode#eval" } ) do |f| %>
    <%= f.label :mode %>
    <%= f.select :mode, Game.modes, { autofocus: true, required: true }, data: { game_mode_target: "mode" } %>
    <div data-game-mode-target="level" style="display: none" >
      <%= f.label :level, "Machine Level" %>
      <%= f.select :level, Game.levels, selected: nil %>
    </div>
    <%= f.submit "Start Game" %>
  <% end %>
</div>

app/views/games/show.html.erb
<%= turbo_stream_from "game" %>
<%= render "games/game", game: @game %>